In [35]:
import pandas as pd

pd.set_option('display.max_columns', None)  # 모든 컬럼 출력
pd.set_option('display.width', 1000)  # 출력 너비 지정
pd.set_option('display.unicode.east_asian_width', True)  # 모든 컬럼 출력

# CSV 파일을 pandas로 읽는다.
# 공공데이터 포털에서 다운로드 받은 bike02.csv 파일 읽는 방법
# encoding= 'cp949'
df = pd.read_csv('greenData/bike02.csv', encoding= 'cp949')

In [31]:
# 상위10개출력한다.
print("상위 10개 데이터")
df.head(10)

상위 10개 데이터

         대여일자    대여건수
0  2025-07-01  132914
1  2025-07-02  151653
2  2025-07-03  151092
3  2025-07-04  151367
4  2025-07-05  118354
5  2025-07-06  106785
6  2025-07-07  146664
7  2025-07-08  115371
8  2025-07-09  136307
9  2025-07-10  139733

In [17]:
# 대여건수가1000 이상인데이터만추출
print("대여건수 1000 이상")
df[df['대여건수'] >= 1000]

대여건수 1000 이상

           대여일자    대여건수
0    2025-07-01  132914
1    2025-07-02  151653
2    2025-07-03  151092
3    2025-07-04  151367
4    2025-07-05  118354
..          ...     ...
179  2025-12-27   42381
180  2025-12-28   40774
181  2025-12-29   66652
182  2025-12-30   71026
183  2025-12-31   55570

[184 rows x 2 columns]

In [37]:
# 대여건수기준내림차순정렬
print("대여건수 내림차순")
df
df.sort_values(by='대여건수', ascending=False)

대여건수 내림차순

       대여일자  대여건수
87   2025-09-26    176011
93   2025-10-02    175022
84   2025-09-23    173588
91   2025-09-30    170957
92   2025-10-01    169645
..          ...       ...
98   2025-10-07     26673
43   2025-08-13     26358
165  2025-12-13     19152
101  2025-10-10     13940
97   2025-10-06     10493

[184 rows x 2 columns]

In [53]:
# 전체대여건수합계구하기
print(f"전체 대여 건수 합계 : {df['대여건수'].sum() :,}")

전체 대여 건수 합계 : 19,647,762

In [52]:
# 평균대여건수구하기
print(f"평균 대여 건수 : {df['대여건수'].mean() : ,.2f}")

평균 대여 건수 :  106,781.32

In [57]:
# 가장대여건수가많은날짜찾기
print(f"대여건수 가장 많은 날짜 : {df.sort_values(by='대여건수', ascending=False).iloc[0]['대여일자']}")

대여건수 가장 많은 날짜 : 2025-09-26

In [60]:
# 미세먼지 데이터 분석
# 일시	구분	미세먼지(PM10)	초미세먼지(PM25)

In [91]:
import pandas as pd

df = pd.read_csv('greenData/pm10.csv', encoding= 'cp949')
# 구분컬럼의데이터중'평균'인행을제외하여실제자치구데이터만남깁니다. (데이터전처리)
print('--- 미세먼지 및 초미세먼지 주의 지역 ---')
# df.drop(df['미세먼지(PM10)'].mean())  # 틀림 
disc = df[df['구분'] != '평균']

# 미세먼지(PM10) 농도가 25 이상이면서 동시에초미세먼지(PM25) 농도가 15 이상인 '주의 요망' 
# df[df['미세먼지(PM10)']>=25]
# df[df['초미세먼지(PM25)']>= 15]
condition = (disc['미세먼지(PM10)'] >= 25) & (disc['초미세먼지(PM25)'] >= 15)
condi02 = disc[condition]

# 조건에맞는지역의구분, 미세먼지(PM10), 초미세먼지(PM25) 컬럼만 선택해 출력하세요.
# del df['일시']  # 좋지않은 방법이라함!
# df
result = condi02[['구분', '미세먼지(PM10)', '초미세먼지(PM25)']]
print(result)

--- 미세먼지 및 초미세먼지 주의 지역 ---
            구분  미세먼지(PM10)  초미세먼지(PM25)
5         관악구            25.0              17.0
9         노원구            28.0              16.0
14      서대문구            31.0              16.0
15        서초구            31.0              15.0
19        양천구            25.0              15.0
...          ...             ...               ...
228377  영등포구            32.0              26.0
228378    용산구            35.0              25.0
228380    종로구            28.0              26.0
228381      중구            26.0              26.0
228382    중랑구            28.0              23.0

[100203 rows x 3 columns]

In [ ]:
# 교통사고데이터분석

In [138]:
import pandas as pd

df = pd.read_csv('greenData/accident.csv', encoding= 'cp949')

# pandas 에서 날짜를 추출하는 함수 종류
# csv 에 입력된 모든 날짜 및 숫자는 문자열 데이터 타입이다.
# 날짜형식으로 형변환하는 함수 : datetime()
# 사고일자의 월 출력
# 년 : df.year, 월 : df.month, 일 : df.day, 시 : df.hour, 분 : df.minute, 초 : second
# 요일을 숫자로 반환 : df.dayofweek (0:원 ~ 6일)
# 요일 이름이 문자열 ('Monday') : df.day_name()
# 분기(1분기~4분기) : df.quarter

# 사고일자 컬럼을 datetime 형식으로 변환하고, 이를 활용하여 '사고월'이라는 새로운 파생변수(컬럼)를 
# 생성하세요.
print('--- 월별 사고 발생 건수 ---')
df['사고일자'] = pd.to_datetime(df['사고일자'])
df['사고월'] = df['사고일자'].dt.month

# 월별 사고건수를 집계하여 어느월에 사고가 가장 많이 발생했는지 확인하세요.
# groupby().count() : 데이터가 비어있지 않은 값이 개수를 센다
# broupby().size() : 그룹별 전체 행의 개수를 센다. (비어있어도 셈)

sago = df.groupby('사고월')['사고월'].count()
# ┖> 빈값이 들어있으면 빈 값의 행을 무시하기때문에 빈 값을 세고싶다면 size
# sago = df.groupby('사고월').size()
sagoMonth = sago.idxmax()  # idxmax : 가장 큰 값이 들어있는 위치(인덱스 이름)에 접근하여 가져옴

print(sago)
print(f"사고가 가장 많은 월 : {sagoMonth}월", end=' / ')
print(f"발생 건수 : {sago.max()}건")

print()

# 사망자수와 부상자수를 더하여 '사상자수'라는 파생변수를 생성하세요.
print('--- 사상자수 기준 상위 5개 위험 노선 ---')
df['사상자수'] = df['사망'] + df['부상']

# 노선명별로 그룹화하여 '사상자수'의 총합을 구하고, 사상자가 가장 많이 발생한 상위5개 노선을
# 내림차순으로 출력하세요.
result = df.groupby('노선명')['사상자수'].sum().sort_values(ascending = False).head(5)
print(result)

# (보너스) 사고 원인이'졸음'이면서사망자가1명이상발생한치명적인사고는총몇건인지구하세요.
print('--- 졸은운전 중 사망자가 발생한 치명적 사고 건수 ---')
result02 = len(df[(df['원인'] == '졸음') & (df['사망'] >= 1)])
print(f"{result02}건")

--- 월별 사고 발생 건수 ---
사고월
1     349
2     326
3     384
4     418
5     400
6     405
7     413
8     429
9     463
10    380
11    378
12    366
Name: 사고월, dtype: int64
사고가 가장 많은 월 : 9월 / 발생 건수 : 463건

--- 사상자수 기준 상위 5개 위험 노선 ---
노선명
경부선        620
중부선        293
중부내륙선    279
영동선        274
서해안선      274
Name: 사상자수, dtype: int64
--- 졸은운전 중 사망자가 발생한 치명적 사고 건수 ---
88건